### ISSUE TITLE
Wiki missing how to create named geometry

### ISSUE THREAD

**Issue by ghost** [Sweets/custard#33]
The wiki currently doesn't have an example of creating a named geometry.

Something like this would be useful:

> To create a geometry named "foobar" defined as a 1-cell wide, 2-cell tall rectangle,
> offset by 3 cell from the left and 4 cells from the top on the "HDMI-0"
> monitor's grid:
> `$ custard - geometry HDMI-0 foobar 1x2 3,4`

**Comment by Sweets** [comment]
👍 Once I get time I'll add it to the wiki

**Comment by Sweets** [comment]
https://github.com/Sweets/custard/wiki/Geometries
