### ISSUE TITLE
Some way to get rid of the sleep 2 before starting the config

### ISSUE THREAD

**Issue by buffet** [Sweets/custard#9]
custardctl should block if custard isn't started yet. Alternatively add a command that blocks, to put at the beginning of the file.

**Comment by Sweets** [comment]
custardctl blocking could be a good idea, though there's no guarantee that the UNIX socket will come alive during the time it waits.

A better approach would be to have custard try and call some config file on-start with a flag. I'm not too particularly interested in implementing the code for having a `-c` flag and handling files, but I'd do it eventually.

**Comment by buffet** [comment]
Pretty much just what we just spoke about, for future reference:

Maybe have custard execute it, since it knows when it's ready.

`exec custard` either does nothing by itself or executes a standard configuration (`~/.config/custard/config` or something).

`exec custard -c=/path/to/config` executes the config when loaded.
